name: kate.schutt.art
favicon: null
layout_spectrum: 0.9336198305245489
typography_spectrum: 0.17497928929515183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.011653082445263863
  lightness: 0.9616374648176134
  saturation: 0.08653902797959745
  rhythmicContrast: 0.447215459542349
purpose: []
